import { prisma } from '@/lib/db/prisma';
import type { Prisma } from '@prisma/client';

const patientEhrSelect = {
  id: true,
  code: true,
  fullName: true,
  arabicName: true,
  phone: true,
  status: true,
  gender: true,
  dateOfBirth: true,
  nationalId: true,
  passportNumber: true,
  bloodGroup: true,
  maritalStatus: true,
  preferredLanguage: true,
  religion: true,
  occupation: true,
  insuranceProvider: true,
  insuranceMemberId: true,
  insurancePolicyNumber: true,
  insuranceExpiry: true,
  dnrStatus: true,
  registrationDate: true,
  addressDetail: true,
  landmark: true,
  gpsLatitude: true,
  gpsLongitude: true,
  addressMapUrl: true,
  emergencyContactName: true,
  emergencyContactPhone: true,
  emergencyContactRelation: true,
  primaryCaregiver: true,
  primaryCaregiverPhone: true,
  primaryCaregiverWhatsapp: true,
  primaryCaregiverEmail: true,
  caregiverRelation: true,
  chiefComplaint: true,
  notes: true,
  area: {
    select: {
      id: true,
      name: true,
      governorate: true,
    },
  },
  family: {
    select: {
      id: true,
      code: true,
      notes: true,
    },
  },
  medicalHistories: {
    where: { deletedAt: null },
    orderBy: { createdAt: 'desc' },
    take: 16,
    select: {
      id: true,
      conditionName: true,
      onsetDate: true,
      status: true,
      notes: true,
      createdAt: true,
    },
  },
  caregivers: {
    where: { deletedAt: null },
    orderBy: { isPrimary: 'desc' },
    take: 12,
    select: {
      id: true,
      fullName: true,
      relationship: true,
      phoneNumber: true,
      whatsappNumber: true,
      email: true,
      isPrimary: true,
      isAuthorized: true,
      notes: true,
      createdAt: true,
    },
  },
  socialHistories: {
    where: { deletedAt: null },
    orderBy: { recordedAt: 'desc' },
    take: 12,
    select: {
      id: true,
      smokingStatus: true,
      alcoholUse: true,
      mobility: true,
      livingConditions: true,
      caregiverSupport: true,
      functionalIndependence: true,
      notes: true,
      recordedAt: true,
      enteredByStaff: { select: { name: true } },
    },
  },
  vaccinationRecords: {
    where: { deletedAt: null },
    orderBy: { administeredOn: 'desc' },
    take: 20,
    select: {
      id: true,
      vaccineName: true,
      doseNumber: true,
      administeredOn: true,
      facilityName: true,
      nextDueDate: true,
      notes: true,
      createdAt: true,
    },
  },
  riskFlags: {
    orderBy: [{ isActive: 'desc' }, { flaggedAt: 'desc' }],
    take: 24,
    select: {
      id: true,
      code: true,
      label: true,
      severity: true,
      isActive: true,
      flaggedAt: true,
      resolvedAt: true,
      notes: true,
      source: true,
      flaggedByStaff: { select: { name: true } },
      resolvedByStaff: { select: { name: true } },
    },
  },
  careTasks: {
    where: { deletedAt: null },
    orderBy: [{ status: 'asc' }, { dueAt: 'asc' }, { createdAt: 'desc' }],
    take: 32,
    select: {
      id: true,
      taskType: true,
      title: true,
      description: true,
      priority: true,
      status: true,
      dueAt: true,
      completedAt: true,
      sourceModule: true,
      createdAt: true,
      assignedToStaff: { select: { name: true, role: true } },
      createdByStaff: { select: { name: true } },
    },
  },
  labOrders: {
    orderBy: { orderedAt: 'desc' },
    take: 20,
    select: {
      id: true,
      testName: true,
      clinicalReason: true,
      priority: true,
      status: true,
      orderedAt: true,
      targetDate: true,
      resultSummary: true,
      notes: true,
      orderedByStaff: { select: { name: true } },
    },
  },
  imagingOrders: {
    orderBy: { orderedAt: 'desc' },
    take: 20,
    select: {
      id: true,
      studyName: true,
      modality: true,
      bodyPart: true,
      clinicalReason: true,
      priority: true,
      status: true,
      orderedAt: true,
      targetDate: true,
      resultSummary: true,
      orderedByStaff: { select: { name: true } },
    },
  },
  nursingOrders: {
    orderBy: { orderedAt: 'desc' },
    take: 20,
    select: {
      id: true,
      orderTitle: true,
      instructions: true,
      frequency: true,
      startDate: true,
      endDate: true,
      priority: true,
      status: true,
      orderedAt: true,
      orderedByStaff: { select: { name: true } },
    },
  },
  physioOrders: {
    orderBy: { orderedAt: 'desc' },
    take: 20,
    select: {
      id: true,
      orderTitle: true,
      protocol: true,
      frequency: true,
      sessionCount: true,
      goals: true,
      priority: true,
      status: true,
      orderedAt: true,
      orderedByStaff: { select: { name: true } },
    },
  },
  medicationOrders: {
    orderBy: { orderedAt: 'desc' },
    take: 20,
    select: {
      id: true,
      medicationName: true,
      dose: true,
      frequency: true,
      route: true,
      isPrn: true,
      startDate: true,
      endDate: true,
      instructions: true,
      priority: true,
      status: true,
      orderedAt: true,
      orderedByStaff: { select: { name: true } },
    },
  },
  visits: {
    orderBy: { scheduledDate: 'desc' },
    take: 10,
    select: {
      id: true,
      code: true,
      scheduledDate: true,
      status: true,
      visitType: true,
      service: { select: { name: true } },
    },
  },
  allergies: {
    where: { deletedAt: null },
    orderBy: { createdAt: 'desc' },
    take: 12,
    select: {
      id: true,
      allergen: true,
      severity: true,
      reaction: true,
      createdAt: true,
    },
  },
  medications: {
    where: { deletedAt: null },
    orderBy: { createdAt: 'desc' },
    take: 12,
    select: {
      id: true,
      medicationName: true,
      dose: true,
      frequency: true,
      isActive: true,
      createdAt: true,
      startDate: true,
    },
  },
  progressNotes: {
    where: { deletedAt: null },
    orderBy: { createdAt: 'desc' },
    take: 10,
    select: {
      id: true,
      noteBody: true,
      createdAt: true,
      signedOffAt: true,
      signedOffByStaffId: true,
      addendums: {
        orderBy: { createdAt: 'desc' },
        select: {
          id: true,
          addendumBody: true,
          createdAt: true,
          enteredByStaff: { select: { name: true } },
        },
      },
    },
  },
  carePlans: {
    orderBy: { updatedAt: 'desc' },
    take: 6,
    select: {
      id: true,
      code: true,
      planName: true,
      startDate: true,
      endDate: true,
      totalVisitsPlanned: true,
      status: true,
      notes: true,
      updatedAt: true,
    },
  },
  diagnoses: {
    where: { deletedAt: null },
    orderBy: { createdAt: 'desc' },
    take: 12,
    select: {
      id: true,
      diagnosisName: true,
      icd10Code: true,
      diagnosedOn: true,
      status: true,
      notes: true,
      enteredByStaff: { select: { name: true } },
    },
  },
  vitalSigns: {
    where: { deletedAt: null },
    orderBy: { measuredAt: 'desc' },
    take: 12,
    select: {
      id: true,
      measuredAt: true,
      systolicBp: true,
      diastolicBp: true,
      heartRate: true,
      oxygenSaturation: true,
      temperatureC: true,
      weightKg: true,
      notes: true,
    },
  },
  physioSessionReports: {
    where: { deletedAt: null },
    orderBy: { sessionDate: 'desc' },
    take: 16,
    select: {
      id: true,
      sessionDate: true,
      sessionNumber: true,
      interventions: true,
      response: true,
      painScoreBefore: true,
      painScoreAfter: true,
      nextSessionDate: true,
      enteredByStaff: { select: { name: true } },
    },
  },
  nurseDailyReports: {
    where: { deletedAt: null },
    orderBy: { reportDate: 'desc' },
    take: 16,
    select: {
      id: true,
      reportDate: true,
      shiftType: true,
      generalCondition: true,
      nursingNotes: true,
      escalationFlag: true,
      escalationReason: true,
      enteredByStaff: { select: { name: true } },
    },
  },
  careTeamMessages: {
    orderBy: { createdAt: 'desc' },
    take: 16,
    select: {
      id: true,
      channelType: true,
      visibilityScope: true,
      messageBody: true,
      requiresFollowUp: true,
      followUpDueAt: true,
      createdAt: true,
      authorStaff: { select: { name: true, role: true } },
    },
  },
  callRoutingTickets: {
    orderBy: { createdAt: 'desc' },
    take: 12,
    select: {
      id: true,
      sourceChannel: true,
      reasonCategory: true,
      triagePriority: true,
      status: true,
      targetCallbackAt: true,
      createdAt: true,
    },
  },
  aiTriageCases: {
    orderBy: { createdAt: 'desc' },
    take: 10,
    select: {
      id: true,
      symptomSummary: true,
      urgencyLevel: true,
      recommendedDisposition: true,
      recommendedSpecialty: true,
      riskScore: true,
      status: true,
      createdAt: true,
      submittedByStaff: { select: { name: true } },
    },
  },
  documents: {
    where: { deletedAt: null },
    orderBy: { createdAt: 'desc' },
    take: 10,
    select: {
      id: true,
      title: true,
      category: true,
      createdAt: true,
    },
  },
  staffAssignments: {
    where: { isActive: true },
    orderBy: { assignedAt: 'desc' },
    select: {
      id: true,
      assignedAt: true,
      staff: {
        select: {
          id: true,
          name: true,
          email: true,
          role: true,
        },
      },
    },
  },
} satisfies Prisma.PatientSelect;

export async function getPatientEhrSnapshot(patientId: string) {
  return prisma.patient.findFirst({
    where: { id: patientId, deletedAt: null },
    select: patientEhrSelect,
  });
}

export type PatientEhrSnapshot = NonNullable<Awaited<ReturnType<typeof getPatientEhrSnapshot>>>;