import { Prisma, PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function upsertDoctorProfiles(): Promise<void> {
  await prisma.doctor.upsert({
    where: { id: 101 },
    update: {
      slug: 'reem-ragab',
      image: 'assets/img/doctor-grid-optimized/reem-rajab.webp',
      rating: 0,
      gender: 'Female',
      location: 'Cairo, Egypt',
      experienceYears: 2,
      successRate: 'Not specified',
      avgWaitTime: 'Not specified',
      totalPatients: 'Not specified',
      availabilityStatus: 'Check availability',
      availabilityBadgeClass: '',
      specialityColorClass: 'active-bar-success',
      specialityTextClass: 'text-success',
      duration: 'By appointment',
      channels: ['Home'],
      languages: ['Arabic'],
      clinics: [],
      areaCoverage: [
        'Fifth Settlement (التجمع الخامس)',
        'New Cairo (القاهرة الجديدة)',
        'Heliopolis (مصر الجديدة)',
        'Sheraton (الشيراتون)',
        'Nasr City (مدينة نصر)',
        'Maadi (المعادي)',
        'Mokattam (المقطم)',
      ],
      clinicDetails: [],
      testimonials: [],
      workHistory: Prisma.JsonNull,
      priceTelemedicine: 'N/A',
      priceHomeVisit: 'N/A',
      priceClinicVisit: 'N/A',
      consultationFee: 'N/A',
      maxConsultationFee: 'N/A',
      nameEn: 'Reem Ragab',
      specialityEn: 'Physical Therapy & Rehabilitation',
      professionalTitleEn:
        'Physiotherapist focused on orthopedic, post-operative, and general surgery rehabilitation cases',
      bioEn:
        "Reem Ragab is a physiotherapist and a 2024 graduate of the Faculty of Physical Therapy at Cairo University, where she earned her bachelor's degree with an excellent grade. Since graduation, she has been building practical clinical experience with a focus on orthopedic cases, post-operative rehabilitation, and general surgery physiotherapy care.",
      certificationsEn: [],
      educationEn: [
        {
          year: '2024',
          degree: 'Bachelor of Physical Therapy (Excellent grade)',
          university: 'Cairo University',
        },
      ],
      nameAr: 'ريم رجب',
      specialityAr: 'العلاج الطبيعي وإعادة التأهيل',
      professionalTitleAr: 'أخصائية علاج طبيعي تركز على حالات العظام والتأهيل بعد العمليات وحالات الجراحة العامة',
      bioAr:
        'ريم رجب أخصائية علاج طبيعي، تخرجت في كلية العلاج الطبيعي بجامعة القاهرة عام 2024 بتقدير امتياز. منذ التخرج وهي تبني خبرة عملية في الرعاية الإكلينيكية مع تركيز على حالات العظام، والتأهيل بعد العمليات، وحالات الجراحة العامة من منظور العلاج الطبيعي.',
      certificationsAr: [],
      educationAr: [
        {
          year: '2024',
          degree: 'بكالوريوس العلاج الطبيعي (تقدير امتياز)',
          university: 'جامعة القاهرة',
        },
      ],
      isActive: true,
    },
    create: {
      id: 101,
      slug: 'reem-ragab',
      image: 'assets/img/doctor-grid-optimized/reem-rajab.webp',
      rating: 0,
      gender: 'Female',
      location: 'Cairo, Egypt',
      experienceYears: 2,
      successRate: 'Not specified',
      avgWaitTime: 'Not specified',
      totalPatients: 'Not specified',
      availabilityStatus: 'Check availability',
      availabilityBadgeClass: '',
      specialityColorClass: 'active-bar-success',
      specialityTextClass: 'text-success',
      duration: 'By appointment',
      channels: ['Home'],
      languages: ['Arabic'],
      clinics: [],
      areaCoverage: [
        'Fifth Settlement (التجمع الخامس)',
        'New Cairo (القاهرة الجديدة)',
        'Heliopolis (مصر الجديدة)',
        'Sheraton (الشيراتون)',
        'Nasr City (مدينة نصر)',
        'Maadi (المعادي)',
        'Mokattam (المقطم)',
      ],
      clinicDetails: [],
      testimonials: [],
      workHistory: Prisma.JsonNull,
      priceTelemedicine: 'N/A',
      priceHomeVisit: 'N/A',
      priceClinicVisit: 'N/A',
      consultationFee: 'N/A',
      maxConsultationFee: 'N/A',
      nameEn: 'Reem Ragab',
      specialityEn: 'Physical Therapy & Rehabilitation',
      professionalTitleEn:
        'Physiotherapist focused on orthopedic, post-operative, and general surgery rehabilitation cases',
      bioEn:
        "Reem Ragab is a physiotherapist and a 2024 graduate of the Faculty of Physical Therapy at Cairo University, where she earned her bachelor's degree with an excellent grade. Since graduation, she has been building practical clinical experience with a focus on orthopedic cases, post-operative rehabilitation, and general surgery physiotherapy care.",
      certificationsEn: [],
      educationEn: [
        {
          year: '2024',
          degree: 'Bachelor of Physical Therapy (Excellent grade)',
          university: 'Cairo University',
        },
      ],
      nameAr: 'ريم رجب',
      specialityAr: 'العلاج الطبيعي وإعادة التأهيل',
      professionalTitleAr: 'أخصائية علاج طبيعي تركز على حالات العظام والتأهيل بعد العمليات وحالات الجراحة العامة',
      bioAr:
        'ريم رجب أخصائية علاج طبيعي، تخرجت في كلية العلاج الطبيعي بجامعة القاهرة عام 2024 بتقدير امتياز. منذ التخرج وهي تبني خبرة عملية في الرعاية الإكلينيكية مع تركيز على حالات العظام، والتأهيل بعد العمليات، وحالات الجراحة العامة من منظور العلاج الطبيعي.',
      certificationsAr: [],
      educationAr: [
        {
          year: '2024',
          degree: 'بكالوريوس العلاج الطبيعي (تقدير امتياز)',
          university: 'جامعة القاهرة',
        },
      ],
      isActive: true,
    },
  });

  await prisma.doctor.upsert({
    where: { id: 102 },
    update: {
      slug: 'menna-m-yahia',
      image: 'assets/img/doctor-grid-optimized/menna-yahia.webp',
      rating: 0,
      gender: 'Female',
      location: 'Cairo, Egypt',
      experienceYears: 2,
      successRate: 'Not specified',
      avgWaitTime: 'Not specified',
      totalPatients: 'Not specified',
      availabilityStatus: 'Check availability',
      availabilityBadgeClass: '',
      specialityColorClass: 'active-bar-success',
      specialityTextClass: 'text-success',
      duration: 'By appointment',
      channels: ['Home'],
      languages: ['Arabic'],
      clinics: [],
      areaCoverage: ['Nasr City (مدينة نصر)', 'Maadi (المعادي)'],
      clinicDetails: [],
      testimonials: [],
      workHistory: Prisma.JsonNull,
      priceTelemedicine: 'N/A',
      priceHomeVisit: 'N/A',
      priceClinicVisit: 'N/A',
      consultationFee: 'N/A',
      maxConsultationFee: 'N/A',
      nameEn: 'Menna M. Yahia',
      specialityEn: 'Physical Therapy & Rehabilitation',
      professionalTitleEn:
        'Physiotherapist with 2 years of experience in orthopedic and post-operative rehabilitation care',
      bioEn:
        "Menna M. Yahia is an experienced physiotherapist with 2 years of experience, working mainly with general orthopedic cases and common rehabilitation needs including osteoarthritis, shoulder conditions, and post-operative rehab cases. She holds a bachelor's degree from Heliopolis University.",
      certificationsEn: [],
      educationEn: [
        {
          year: 'Not specified',
          degree: 'Bachelor of Physical Therapy',
          university: 'Heliopolis University',
        },
      ],
      nameAr: 'منة م. يحيى',
      specialityAr: 'العلاج الطبيعي وإعادة التأهيل',
      professionalTitleAr: 'أخصائية علاج طبيعي بخبرة سنتين في حالات العظام والتأهيل بعد العمليات',
      bioAr:
        'منة م. يحيى أخصائية علاج طبيعي لديها خبرة سنتين، وتعمل بشكل أساسي مع حالات العظام العامة والحالات الشائعة مثل خشونة المفاصل، وحالات الكتف، والتأهيل بعد العمليات. حاصلة على درجة البكالوريوس من جامعة هليوبوليس.',
      certificationsAr: [],
      educationAr: [
        {
          year: 'غير محدد',
          degree: 'بكالوريوس العلاج الطبيعي',
          university: 'جامعة هليوبوليس',
        },
      ],
      isActive: true,
    },
    create: {
      id: 102,
      slug: 'menna-m-yahia',
      image: 'assets/img/doctor-grid-optimized/menna-yahia.webp',
      rating: 0,
      gender: 'Female',
      location: 'Cairo, Egypt',
      experienceYears: 2,
      successRate: 'Not specified',
      avgWaitTime: 'Not specified',
      totalPatients: 'Not specified',
      availabilityStatus: 'Check availability',
      availabilityBadgeClass: '',
      specialityColorClass: 'active-bar-success',
      specialityTextClass: 'text-success',
      duration: 'By appointment',
      channels: ['Home'],
      languages: ['Arabic'],
      clinics: [],
      areaCoverage: ['Nasr City (مدينة نصر)', 'Maadi (المعادي)'],
      clinicDetails: [],
      testimonials: [],
      workHistory: Prisma.JsonNull,
      priceTelemedicine: 'N/A',
      priceHomeVisit: 'N/A',
      priceClinicVisit: 'N/A',
      consultationFee: 'N/A',
      maxConsultationFee: 'N/A',
      nameEn: 'Menna M. Yahia',
      specialityEn: 'Physical Therapy & Rehabilitation',
      professionalTitleEn:
        'Physiotherapist with 2 years of experience in orthopedic and post-operative rehabilitation care',
      bioEn:
        "Menna M. Yahia is an experienced physiotherapist with 2 years of experience, working mainly with general orthopedic cases and common rehabilitation needs including osteoarthritis, shoulder conditions, and post-operative rehab cases. She holds a bachelor's degree from Heliopolis University.",
      certificationsEn: [],
      educationEn: [
        {
          year: 'Not specified',
          degree: 'Bachelor of Physical Therapy',
          university: 'Heliopolis University',
        },
      ],
      nameAr: 'منة م. يحيى',
      specialityAr: 'العلاج الطبيعي وإعادة التأهيل',
      professionalTitleAr: 'أخصائية علاج طبيعي بخبرة سنتين في حالات العظام والتأهيل بعد العمليات',
      bioAr:
        'منة م. يحيى أخصائية علاج طبيعي لديها خبرة سنتين، وتعمل بشكل أساسي مع حالات العظام العامة والحالات الشائعة مثل خشونة المفاصل، وحالات الكتف، والتأهيل بعد العمليات. حاصلة على درجة البكالوريوس من جامعة هليوبوليس.',
      certificationsAr: [],
      educationAr: [
        {
          year: 'غير محدد',
          degree: 'بكالوريوس العلاج الطبيعي',
          university: 'جامعة هليوبوليس',
        },
      ],
      isActive: true,
    },
  });

  await prisma.doctor.upsert({
    where: { id: 103 },
    update: {
      slug: 'mohamed-mahmoud-hamza',
      image: 'assets/img/doctor-grid-optimized/hamza.webp',
      rating: 0,
      gender: 'Male',
      location: 'Cairo, Egypt',
      experienceYears: 3,
      successRate: 'Not specified',
      avgWaitTime: 'Not specified',
      totalPatients: 'Not specified',
      availabilityStatus: 'Check availability',
      availabilityBadgeClass: '',
      specialityColorClass: 'active-bar-success',
      specialityTextClass: 'text-success',
      duration: 'By appointment',
      channels: ['Home', 'Clinic'],
      languages: ['Arabic'],
      clinics: ['Clinic location available via map link'],
      areaCoverage: [
        'Fifth Settlement (التجمع الخامس)',
        'New Cairo (القاهرة الجديدة)',
        'Obour (العبور)',
      ],
      clinicDetails: [
        {
          name: 'Clinic location',
          hours: 'Not specified',
          slots: 'Not specified',
          mapUrl: 'https://maps.app.goo.gl/E3tCgHexcdGo696R9',
          address: 'Not specified',
          location: 'Cairo, Egypt',
        },
      ],
      testimonials: [],
      workHistory: Prisma.JsonNull,
      priceTelemedicine: 'N/A',
      priceHomeVisit: 'N/A',
      priceClinicVisit: 'N/A',
      consultationFee: 'N/A',
      maxConsultationFee: 'N/A',
      nameEn: 'Mohamed Mahmoud Hamza',
      specialityEn: 'Neurological Physical Therapy',
      professionalTitleEn: 'Physical therapist specializing in neurological cases',
      bioEn:
        'Mohamed Mahmoud Hamza is a physical therapist specializing in neurological cases, with 3 years of experience in neuro-focused physiotherapy care.',
      certificationsEn: [],
      educationEn: [],
      nameAr: 'محمد محمود حمزة',
      specialityAr: 'العلاج الطبيعي للحالات العصبية',
      professionalTitleAr: 'أخصائي علاج طبيعي متخصص في حالات المخ والأعصاب',
      bioAr:
        'محمد محمود حمزة أخصائي علاج طبيعي متخصص في حالات المخ والأعصاب، ولديه خبرة 3 سنوات في الرعاية التأهيلية للحالات العصبية.',
      certificationsAr: [],
      educationAr: [],
      isActive: true,
    },
    create: {
      id: 103,
      slug: 'mohamed-mahmoud-hamza',
      image: 'assets/img/doctor-grid-optimized/hamza.webp',
      rating: 0,
      gender: 'Male',
      location: 'Cairo, Egypt',
      experienceYears: 3,
      successRate: 'Not specified',
      avgWaitTime: 'Not specified',
      totalPatients: 'Not specified',
      availabilityStatus: 'Check availability',
      availabilityBadgeClass: '',
      specialityColorClass: 'active-bar-success',
      specialityTextClass: 'text-success',
      duration: 'By appointment',
      channels: ['Home', 'Clinic'],
      languages: ['Arabic'],
      clinics: ['Clinic location available via map link'],
      areaCoverage: [
        'Fifth Settlement (التجمع الخامس)',
        'New Cairo (القاهرة الجديدة)',
        'Obour (العبور)',
      ],
      clinicDetails: [
        {
          name: 'Clinic location',
          hours: 'Not specified',
          slots: 'Not specified',
          mapUrl: 'https://maps.app.goo.gl/E3tCgHexcdGo696R9',
          address: 'Not specified',
          location: 'Cairo, Egypt',
        },
      ],
      testimonials: [],
      workHistory: Prisma.JsonNull,
      priceTelemedicine: 'N/A',
      priceHomeVisit: 'N/A',
      priceClinicVisit: 'N/A',
      consultationFee: 'N/A',
      maxConsultationFee: 'N/A',
      nameEn: 'Mohamed Mahmoud Hamza',
      specialityEn: 'Neurological Physical Therapy',
      professionalTitleEn: 'Physical therapist specializing in neurological cases',
      bioEn:
        'Mohamed Mahmoud Hamza is a physical therapist specializing in neurological cases, with 3 years of experience in neuro-focused physiotherapy care.',
      certificationsEn: [],
      educationEn: [],
      nameAr: 'محمد محمود حمزة',
      specialityAr: 'العلاج الطبيعي للحالات العصبية',
      professionalTitleAr: 'أخصائي علاج طبيعي متخصص في حالات المخ والأعصاب',
      bioAr:
        'محمد محمود حمزة أخصائي علاج طبيعي متخصص في حالات المخ والأعصاب، ولديه خبرة 3 سنوات في الرعاية التأهيلية للحالات العصبية.',
      certificationsAr: [],
      educationAr: [],
      isActive: true,
    },
  });
}

async function main(): Promise<void> {
  console.log('Seeding doctor profiles only...');
  await upsertDoctorProfiles();
  console.log('Doctor-only seed complete.');
}

main()
  .catch((error) => {
    console.error('Doctor-only seed failed:', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
