/**
 * lint:rbac — keep the doc's permission table in sync with the code.
 * ------------------------------------------------------------------
 * The single source of truth is the readable grid in
 * `src/lib/auth/policy/ehr-matrix.ts` (module × role → hidden/read/write/sign).
 *
 * This script DERIVES a granular "action × role" table from that grid — one row
 * per (module, level) — and writes it between the RBAC_MATRIX markers in
 * docs/EHR_ROLE_MATRIX.md §22.
 *
 *   node -r ts-node/register scripts/lint-rbac.ts          → CHECK (CI): exit 1 if stale
 *   node -r ts-node/register scripts/lint-rbac.ts --fix    → WRITE the regenerated table
 *
 * So nobody edits the table by hand: edit the grid, run --fix, commit. CI runs
 * the check and fails the build if the doc and code ever drift apart.
 */

import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { StaffRole } from '@prisma/client';
import {
  EHR_MATRIX,
  ALL_STAFF_ROLES,
  cellForRole,
  meetsCapability,
  type Capability,
  type ModuleKey,
} from '../src/lib/auth/policy/ehr-matrix';

const DOC_PATH = join(__dirname, '..', 'docs', 'EHR_ROLE_MATRIX.md');
const BEGIN = '<!-- RBAC_MATRIX:BEGIN -->';
const END = '<!-- RBAC_MATRIX:END -->';

// Columns sorted alphabetically for a stable, readable table.
const ROLES: StaffRole[] = [...ALL_STAFF_ROLES].sort();
const LEVELS: Capability[] = ['read', 'write', 'sign'];

/** Mark a cell: ★ for the superadmin wildcard, ✅ if the role meets the level, else blank. */
function mark(module: ModuleKey, role: StaffRole, level: Capability): string {
  if (role === 'superadmin') return '★';
  return meetsCapability(cellForRole(module, role).level, level) ? '✅' : '';
}

function buildTable(): string {
  const moduleKeys = Object.keys(EHR_MATRIX) as ModuleKey[];
  const rows: string[] = [];

  for (const moduleKey of moduleKeys) {
    for (const level of LEVELS) {
      // Only emit a row if at least one non-super role actually reaches this level.
      const anyReal = ROLES.some(
        (r) => r !== 'superadmin' && meetsCapability(cellForRole(moduleKey, r).level, level),
      );
      if (!anyReal) continue;

      const cells = ROLES.map((role) => mark(moduleKey, role, level));
      rows.push(`| \`${moduleKey}.${level}\` | ${cells.join(' | ')} |`);
    }
  }

  const header = `| Action | ${ROLES.join(' | ')} |`;
  const divider = `| --- | ${ROLES.map(() => '---').join(' | ')} |`;

  return [
    '',
    '### Action × Role allow matrix',
    '',
    `**${rows.length} actions × ${ROLES.length} roles. ✅ = allowed. blank = denied. ★ = wildcard role.**`,
    '',
    `_Derived from the module grid: each module yields \`*.read\` / \`*.write\` / \`*.sign\` rows by capability._`,
    '',
    header,
    divider,
    ...rows,
    '',
    '_Generated by `npm run lint:rbac` from `src/lib/auth/policy/ehr-matrix.ts`. Do not edit by hand._',
    '',
  ].join('\n');
}

function main(): void {
  const fix = process.argv.includes('--fix');
  const doc = readFileSync(DOC_PATH, 'utf8');

  const beginIdx = doc.indexOf(BEGIN);
  const endIdx = doc.indexOf(END);
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    console.error(`lint:rbac: could not find ${BEGIN} … ${END} markers in EHR_ROLE_MATRIX.md`);
    process.exit(1);
  }

  const before = doc.slice(0, beginIdx + BEGIN.length);
  const after = doc.slice(endIdx);
  const generated = `${before}\n${buildTable()}\n${after}`;

  if (fix) {
    if (generated !== doc) {
      writeFileSync(DOC_PATH, generated, 'utf8');
      console.log('lint:rbac: ✅ regenerated §22 table in EHR_ROLE_MATRIX.md');
    } else {
      console.log('lint:rbac: ✅ already up to date');
    }
    return;
  }

  if (generated !== doc) {
    console.error(
      'lint:rbac: ❌ §22 in EHR_ROLE_MATRIX.md is out of sync with ehr-matrix.ts.\n' +
        '            Run `npm run lint:rbac:fix` and commit the result.',
    );
    process.exit(1);
  }
  console.log('lint:rbac: ✅ doc matches code');
}

main();
