import type { getMedplumPatient } from '@/lib/medplum/patients';
import type { StaffRole } from '@prisma/client';
import type { listPatientEncounters } from '@/lib/medplum/encounters';
import type { listRecentPatientVitals } from '@/lib/medplum/observations';
import type { listPatientClinicalNotes } from '@/lib/medplum/clinical-notes';
import type { getActivePatientCareTeam } from '@/lib/medplum/care-teams';
import type { listPatientTasks } from '@/lib/medplum/tasks';
import type { listPatientCareReports } from '@/lib/medplum/care-reports';
import type { PortalConsentSummary } from '@/lib/medplum/consents';
import type { AllergySummary } from '@/lib/medplum/allergies';
import type { ConditionSummary } from '@/lib/medplum/conditions';
import type { MedicationSummary } from '@/lib/medplum/medications';
import type { MedicationAdministrationSummary } from '@/lib/medplum/medication-administrations';
import type { DocumentSummary } from '@/lib/medplum/documents';
import type { LabOrderSummary, LabResultSummary } from '@/lib/medplum/labs';
import type { AssessmentSummary } from '@/lib/medplum/assessments';
import type { CommunicationSummary } from '@/lib/medplum/communications';
import type { AppointmentSummary } from '@/lib/medplum/appointments';

export type AssignableStaff = {
  id: string;
  name: string;
  email: string;
  role: 'superadmin' | 'admin' | 'operator' | 'doctor' | 'physiotherapist' | 'nurse' | 'finance' | 'viewer';
};

export type AdminPatientFlash = {
  type: 'success' | 'error';
  message: string;
};

export type AdminPatientDetailData = {
  staffRole: StaffRole | null;
  patient: Awaited<ReturnType<typeof getMedplumPatient>> | null;
  localPatient: {
    id: string;
    code: string;
    addressDetail: string | null;
    landmark: string | null;
    addressMapUrl: string | null;
    handoffGeofenceRadiusMeters: number | null;
    temporarilyAwayUntil: string | null;
    temporarilyAwayNote: string | null;
    primaryCaregiverPhone: string | null;
    primaryCaregiverEmail: string | null;
    emergencyContactName: string | null;
    emergencyContactPhone: string | null;
    emergencyContactRelation: string | null;
  } | null;
  error: string | null;
  encounters: Awaited<ReturnType<typeof listPatientEncounters>>;
  encountersError: string | null;
  vitals: Awaited<ReturnType<typeof listRecentPatientVitals>>;
  vitalsError: string | null;
  clinicalNotes: Awaited<ReturnType<typeof listPatientClinicalNotes>>;
  clinicalNotesError: string | null;
  careTeam: Awaited<ReturnType<typeof getActivePatientCareTeam>>;
  careTeamError: string | null;
  assignableStaff: AssignableStaff[];
  tasks: Awaited<ReturnType<typeof listPatientTasks>>;
  tasksError: string | null;
  careReports: Awaited<ReturnType<typeof listPatientCareReports>>;
  careReportsError: string | null;
  conditions: ConditionSummary[];
  conditionsError: string | null;
  allergies: AllergySummary[];
  allergiesError: string | null;
  medications: MedicationSummary[];
  medicationsError: string | null;
  medicationAdministrations: MedicationAdministrationSummary[];
  medicationAdministrationsError: string | null;
  documents: DocumentSummary[];
  documentsError: string | null;
  labOrders: LabOrderSummary[];
  labOrdersError: string | null;
  labResults: LabResultSummary[];
  labResultsError: string | null;
  assessments: AssessmentSummary[];
  assessmentsError: string | null;
  communications: CommunicationSummary[];
  communicationsError: string | null;
  appointments: AppointmentSummary[];
  appointmentsError: string | null;
  nurseShiftAssignments: Array<{
    id: string;
    shiftStartAt: string;
    shiftEndAt: string;
    status: string;
    primaryNurseName: string;
    primaryNurseStaffId: string;
    incomingNurseName: string | null;
    incomingNurseStaffId: string | null;
    acknowledgedAt: string | null;
    escalationTaskId: string | null;
    notes: string | null;
  }>;
  nurseShiftAssignmentsError: string | null;
  caregiverConsents: PortalConsentSummary[];
  caregiverConsentsError: string | null;
};
